# Generated by Django 4.1.7 on 2023-09-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wins',
            new_name='Win',
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='win',
            options={'verbose_name': 'Win', 'verbose_name_plural': 'Wins'},
        ),
        migrations.AddField(
            model_name='artist',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
        migrations.AlterModelTable(
            name='win',
            table='win',
        ),
    ]
