# Generated by Django 4.1.7 on 2023-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0002_rename_wins_win_alter_album_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
